--
-- PostgreSQL database dump
--

\restrict jE2sY3XMReiRCXYW9PYZqHOse5mZkIBc3uCi6VhLcyILgzVon7eyrLvoq3KYIuR

-- Dumped from database version 15.8
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: get_fees_with_payments(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_fees_with_payments() RETURNS TABLE(fee_id bigint, fee_name character varying, fee_amount numeric, payment_id bigint, payment_value numeric, payment_description character varying, payment_created_at timestamp with time zone, payment_updated_at timestamp with time zone, payment_type character varying, has_payment text)
    LANGUAGE plpgsql
    AS $$BEGIN
  RETURN QUERY
  SELECT
    fees.fee_id,
    fees.fee_description,
    fees.fee_amount,
    payments.payment_id,
    payments.payment_value,
    payments.payment_description,
    payments.payment_created_at,
    payments.payment_updated_at,
    payments.payment_type,
    CASE 
      WHEN payments.payment_id IS NOT NULL THEN 'yes'
      ELSE 'no'
    END AS has_payment
  FROM fees
  LEFT JOIN payments ON fees.fee_id = payments.fee_id;
END;$$;


--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$begin
    insert into public.users (
        user_id,
        user_name,
        user_identification,
        user_phone_no,
        user_address,
        user_email,
        user_type,
        user_password,  -- You could skip this if you don't want to store plain passwords
        user_created_at,
        user_updated_at
    )
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'user_name', 'Unknown'),
        coalesce(new.raw_user_meta_data->>'user_identification', 'Unknown'),
        coalesce(new.raw_user_meta_data->>'user_phone_no', 'Unknown'),
        coalesce(new.raw_user_meta_data->>'user_address', 'Unknown'),
        new.email,
        coalesce(new.raw_user_meta_data->>'user_type', 'Unknown'),
        coalesce(new.raw_user_meta_data->>'user_password', 'Unknown'),
        now(),
        now()
    );

    return new;
end;$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin (
    admin_id bigint NOT NULL,
    admin_role character varying NOT NULL,
    user_id character varying
);


--
-- Name: admin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcements (
    announcement_id bigint NOT NULL,
    announcement_title character varying NOT NULL,
    announcement_description character varying,
    announcement_type character varying NOT NULL,
    announcement_created_at timestamp with time zone DEFAULT now() NOT NULL,
    announcement_updated_at timestamp without time zone DEFAULT now(),
    admin_id bigint NOT NULL,
    announcement_image character varying
);


--
-- Name: announcements_announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcements ALTER COLUMN announcement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.claims (
    claim_id bigint NOT NULL,
    "claim_overallStatus" character varying DEFAULT 'Pending'::character varying NOT NULL,
    claim_created_at timestamp with time zone DEFAULT now() NOT NULL,
    claim_updated_at timestamp without time zone DEFAULT now(),
    family_id bigint,
    user_id character varying,
    claim_type character varying,
    claim_reason character varying,
    claim_certificate_url character varying
);


--
-- Name: claim_claim_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.claims ALTER COLUMN claim_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.claim_claim_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: claim_line; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.claim_line (
    "claimLine_id" bigint NOT NULL,
    "claimLine_reason" character varying NOT NULL,
    "claimLine_totalPrice" double precision NOT NULL,
    "claimLine_created_at" timestamp with time zone DEFAULT now() NOT NULL,
    claimline_updated_at timestamp without time zone DEFAULT now(),
    claim_id bigint NOT NULL
);


--
-- Name: claim_line_claimLine_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.claim_line ALTER COLUMN "claimLine_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."claim_line_claimLine_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: family; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.family (
    family_id bigint NOT NULL,
    familymember_name character varying NOT NULL,
    familymember_identification character varying NOT NULL,
    familymember_relationship character varying NOT NULL,
    family_created_at timestamp with time zone DEFAULT now() NOT NULL,
    family_updated_at timestamp without time zone DEFAULT now(),
    user_id character varying
);


--
-- Name: family_family_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.family ALTER COLUMN family_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.family_family_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fees (
    fee_id bigint NOT NULL,
    fee_description character varying NOT NULL,
    fee_due date,
    fee_type character varying NOT NULL,
    fee_created_at timestamp with time zone DEFAULT now() NOT NULL,
    fee_updated_at timestamp without time zone DEFAULT now(),
    admin_id bigint NOT NULL,
    fee_amount numeric
);


--
-- Name: fee_fee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fees ALTER COLUMN fee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_fee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    payment_id bigint NOT NULL,
    payment_value double precision NOT NULL,
    payment_description character varying,
    payment_created_at timestamp with time zone DEFAULT now() NOT NULL,
    payment_updated_at timestamp without time zone DEFAULT now(),
    fee_id bigint,
    user_id character varying,
    payment_type character varying,
    reference_id character varying
);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_name character varying NOT NULL,
    user_identification character varying NOT NULL,
    user_phone_no character varying NOT NULL,
    user_address character varying NOT NULL,
    user_email character varying NOT NULL,
    user_type character varying DEFAULT 'user'::character varying NOT NULL,
    user_password character varying NOT NULL,
    user_created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_updated_at timestamp without time zone DEFAULT now(),
    user_id character varying NOT NULL
);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (admin_id);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (announcement_id);


--
-- Name: claim_line claim_line_claimLine_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claim_line
    ADD CONSTRAINT "claim_line_claimLine_id_key" UNIQUE ("claimLine_id");


--
-- Name: claim_line claim_line_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claim_line
    ADD CONSTRAINT claim_line_pkey PRIMARY KEY ("claimLine_id");


--
-- Name: claims claim_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claim_pkey PRIMARY KEY (claim_id);


--
-- Name: family family_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.family
    ADD CONSTRAINT family_pkey PRIMARY KEY (family_id);


--
-- Name: fees fee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fee_pkey PRIMARY KEY (fee_id);


--
-- Name: fees fees_fee_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fees_fee_id_key UNIQUE (fee_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_email_key UNIQUE (user_email);


--
-- Name: announcements handle_announcements_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_announcements_updated_at BEFORE UPDATE ON public.announcements FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('announcement_updated_at');


--
-- Name: claims handle_claim_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_claim_updated_at BEFORE UPDATE ON public.claims FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('claim_updated_at');


--
-- Name: claim_line handle_claimline_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_claimline_updated_at BEFORE UPDATE ON public.claim_line FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('claimline_updated_at');


--
-- Name: fees handle_fee_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_fee_updated_at BEFORE UPDATE ON public.fees FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('fee_updated_at');


--
-- Name: payments handle_payments_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_payments_updated_at BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('payment_updated_at');


--
-- Name: users handle_user_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER handle_user_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('user_updated_at');


--
-- Name: admin admin_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: announcements announcements_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: claims claim_family_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claim_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.family(family_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: claim_line claim_line_claim_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claim_line
    ADD CONSTRAINT claim_line_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(claim_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: claims claim_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claim_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: family family_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.family
    ADD CONSTRAINT family_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: fees fee_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fees
    ADD CONSTRAINT fee_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin(admin_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: payments payments_fee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_fee_id_fkey FOREIGN KEY (fee_id) REFERENCES public.fees(fee_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: payments payments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: family Allow users to delete their family records; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow users to delete their family records" ON public.family FOR DELETE TO authenticated USING ((( SELECT (auth.uid())::text AS uid) = (user_id)::text));


--
-- Name: family Allow users to insert their family records; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow users to insert their family records" ON public.family FOR INSERT TO authenticated WITH CHECK ((( SELECT (auth.uid())::text AS uid) = (user_id)::text));


--
-- Name: family Allow users to update their family records; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow users to update their family records" ON public.family FOR UPDATE TO authenticated USING ((( SELECT (auth.uid())::text AS uid) = (user_id)::text)) WITH CHECK ((( SELECT (auth.uid())::text AS uid) = (user_id)::text));


--
-- Name: users Allow users to update their own details; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow users to update their own details" ON public.users FOR UPDATE TO authenticated USING ((( SELECT (auth.uid())::text AS uid) = (user_id)::text)) WITH CHECK ((( SELECT (auth.uid())::text AS uid) = (user_id)::text));


--
-- Name: announcements Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.announcements FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE (((users.user_id)::uuid = auth.uid()) AND ((users.user_type)::text = 'admin'::text)))));


--
-- Name: claim_line Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.claim_line FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE (((users.user_id)::uuid = auth.uid()) AND ((users.user_type)::text = 'admin'::text)))));


--
-- Name: claims Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.claims FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: family Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.family FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: fees Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.fees FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE (((users.user_id)::uuid = auth.uid()) AND ((users.user_type)::text = 'admin'::text)))));


--
-- Name: users Enable delete for users based on user_id; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable delete for users based on user_id" ON public.users FOR DELETE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: announcements Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.announcements FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: claim_line Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.claim_line FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: claims Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.claims FOR INSERT WITH CHECK (true);


--
-- Name: family Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.family FOR INSERT WITH CHECK (true);


--
-- Name: fees Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.fees FOR INSERT WITH CHECK (true);


--
-- Name: payments Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.payments FOR INSERT WITH CHECK (true);


--
-- Name: users Enable insert for authenticated users only; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable insert for authenticated users only" ON public.users FOR INSERT WITH CHECK (true);


--
-- Name: admin Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.admin FOR SELECT USING (true);


--
-- Name: announcements Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.announcements FOR SELECT USING (true);


--
-- Name: claim_line Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.claim_line FOR SELECT USING (true);


--
-- Name: claims Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.claims FOR SELECT USING (true);


--
-- Name: family Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.family FOR SELECT USING (true);


--
-- Name: fees Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.fees FOR SELECT USING (true);


--
-- Name: payments Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.payments FOR SELECT USING (true);


--
-- Name: users Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON public.users FOR SELECT USING (true);


--
-- Name: fees Policy update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy update" ON public.fees FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE (((users.user_id)::uuid = auth.uid()) AND ((users.user_type)::text = 'admin'::text)))));


--
-- Name: announcements Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.announcements FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.users
  WHERE (((users.user_id)::uuid = auth.uid()) AND ((users.user_type)::text = 'admin'::text)))));


--
-- Name: claim_line Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.claim_line FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: claims Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.claims FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: family Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.family FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: users Policy with table joins; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Policy with table joins" ON public.users FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM public.users users_1
  WHERE (((users_1.user_id)::uuid = auth.uid()) AND ((users_1.user_type)::text = 'admin'::text)))));


--
-- Name: claims Update for their own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Update for their own" ON public.claims FOR UPDATE USING ((( SELECT (auth.uid())::text AS uid) = (user_id)::text)) WITH CHECK ((( SELECT (auth.uid())::text AS uid) = (user_id)::text));


--
-- Name: admin; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.admin ENABLE ROW LEVEL SECURITY;

--
-- Name: announcements; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

--
-- Name: claim_line; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.claim_line ENABLE ROW LEVEL SECURITY;

--
-- Name: claims; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;

--
-- Name: family; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.family ENABLE ROW LEVEL SECURITY;

--
-- Name: fees; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.fees ENABLE ROW LEVEL SECURITY;

--
-- Name: payments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

--
-- Name: users; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict jE2sY3XMReiRCXYW9PYZqHOse5mZkIBc3uCi6VhLcyILgzVon7eyrLvoq3KYIuR

